spring:
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: ${DB_DIALECT}
  datasource:
    username: ${DB_USERNAME}
    password:  ${DB_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: ${DB_URL}
  liquibase:
    change-log: classpath:db/changelog/postgressql/changelog-master.xml
